//
// ContentSection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ContentSection: Codable {

    public var name: String?
    public var _id: String?
    public var sectionType: String?
    public var collectionType: String?
    public var viewType: String?
    public var monitor: [String]?
    public var cardSizeOffset: Int?
    public var scrollDirection: ScrollDirection?
    public var parentItem: BaseItemDto?

    public init(name: String? = nil, _id: String? = nil, sectionType: String? = nil, collectionType: String? = nil, viewType: String? = nil, monitor: [String]? = nil, cardSizeOffset: Int? = nil, scrollDirection: ScrollDirection? = nil, parentItem: BaseItemDto? = nil) {
        self.name = name
        self._id = _id
        self.sectionType = sectionType
        self.collectionType = collectionType
        self.viewType = viewType
        self.monitor = monitor
        self.cardSizeOffset = cardSizeOffset
        self.scrollDirection = scrollDirection
        self.parentItem = parentItem
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case _id = "Id"
        case sectionType = "SectionType"
        case collectionType = "CollectionType"
        case viewType = "ViewType"
        case monitor = "Monitor"
        case cardSizeOffset = "CardSizeOffset"
        case scrollDirection = "ScrollDirection"
        case parentItem = "ParentItem"
    }

}
